### ISSUE TITLE
New Page: Homepage

### ISSUE THREAD

**Issue by p5quared** [Program-BMCC/club-website#6]
# Basic homepage 1.0 needs to be created.

Note this does not include the nav-bar, which I think makes sense to consider and refer to separately.

Pretty open ended task; I am looking to see if we can source some images but we can just use placeholders like fancy squares or something for the time being.

I think [this site](https://bccompsci.club/) is a good reference to start with.

**Comment by iamalmiir** [comment]
Done. Will merge once when Contact page is done.
